create table empregado( 
    codigo int, 
    nome varchar(60) not null, 
    cpf varchar(14) not null, 
    sexo char(1), 
    datanasc date, 
    logradouro varchar(50), 
    nro int, 
    salario numeric(8,2) not null, 
    depto_num int, 
    codigo_ger int, 
    constraint empregado_pk primary key(codigo), 
    constraint emp_sal_ck check(salario > 0), 
    constraint emp_sexo_ck check(sexo in ('M','F')) 
);

create table departamento(
	numero int,
	nome varchar(20) not null,
	codigo_ger int,
	data_inicio_ger date,
	constraint dapatamento_pk primary key(numero),
	constraint depto_nome_uk unique(nome)
);

alter table departamento add constraint depto_ger_fk
	foreign key(codigo_ger) references empregado(codigo);

alter table empregado add constraint emp_depto_fk foreign key(depto_num)
	references departamento(numero);

alter table empregado add constraint emp_ger_fk foreign key(codigo_ger)
	references empregado(codigo);

--ALTER TABLE
--ADICIONA COLUNAS
alter table empregado add fone varchar(20);

--MODIFICAR COLUNA
alter table empregado alter fone type varchar(16);

--renomear colunas
alter table empregado rename fone to fone_emp;

--apagar coluna
alter table empregado drop fone_emp;

-- renomear constraint
alter table empregado rename constraint emp_ger_fk to emp_gerente_fk;

--renomear tabelas
alter table empregado rename to emp;
alter table emp rename to empregado;

--apagar constraint
alter table empregado drop constraint emp_gerente_fk;

--alterar colunas para not null / null
alter table empregado alter depto_num set not null;
alter table empregado alter depto_num drop default;

--colocar valor default para colunas
alter table empregado alter depto_num set default 10;
alter table empregado alter depto_num drop default;

--utilizados colunas auto incrementaveis
create table teste(
	id serial primary key,
	descricao varchar(20)
);

--formas alternativas com generated
create table aluno(
	id int generated by default as identity,
	nome varchar(100),
	primary key(id)
);

--generated colums
create table produto(
	id serial primary key,
	descricao varchar(80),
	preco numeric(10,2),
	quantidade int,
	valor_total numeric(10,2) generated always as (preco+quantidade) stored
);

-- so funciona a partir da versao 18
create table produto(
	id serial primary key,
	descricao varchar(80),
	preco numeric(10,2),
	quantidade int,
	valor_total numeric(10,2) generated always as (preco*quantidade) virtual



--apaga tabelas
drop table departamento;
drop table empregado;

alter table aluno add id_responsavel int;
alter table aluno add foreign key(id_responsave) references empregado(codigo);

alter table aluno drop constraint aluno_id_responsavelfkey;
alter table departamento drop constraint depto_ger_fk;

drop table empregado
drop table departamento

--apagar tabelas em cascata
drop table departamente cascade;

--apagar database
drop database --aula;


	 


)
